name: Docker Image CI

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag anypay/web3-checkout:${{ github.ref_name }}

      - name: Run tests in docker image
        run: docker run anypay/web3-checkout:${{ github.ref_name }} npm run test

      - name: Push Docker Image
        if: github.event_name == 'push' && github.event_name != 'pull_request'
        run: |
          docker push anypay/web3-checkout:${{ github.ref_name }}

